name: Project test coverage

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Checkout
        uses: actions/checkout@master

      - name: Install dependencies
        run: npm install

      - name: Calculate test coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: npm run test
          coverageLocations: ${{github.workspace}}/coverage/lcov.info:lcov
